apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: postgresql-operator.v0.0.1
  namespace: placeholder
  annotations:
    alm-examples: '[{"apiVersion":"postgresql.baiju.dev/v1alpha1","kind":"Database","metadata":{"name":"demo-database","namespace":"openshift-operators"},"spec":{"image":"docker.io/postgres","imageName":"postgres"}}]'
    capabilities: Full Lifecycle
    categories: 'Database'
    containerImage: REPLACE_IMAGE
    createdAt: 'REPLACE_CREATED_AT'
    description: The operator that manages PostgreSQL databases.
spec:
  displayName: PostgreSQL Database
  description: "The operator that manages PostgreSQL databases."
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAAIAAAACABAMAAAAxEHz4AAAXAnpUWHRSYXcgcHJvZmlsZSB0eXBlIGV4aWYAAHjarZtrduO4koT/YxWzBOINLAfPc2YHs/z5ApRdfshuu7rLty2ZEkkgMzIyAsQ16//+d5v/4V/26TIh5pJqShf/Qg3VNd6U6/53v9ornN9vDp2/3x03rx84Dnle/f1nWo/vN47HPyfk8Dje3x83eTyuUx4Xsq8XPv+87qz38zGix4W8u4/bx9+mPk5o6c10Hv+58bjs4+If/w6ZYMzI9bwzbnnrr/v3fSfPKHz1jdfEb+cTX7zOkejzOVI/x8+8hu5JAF/ffYjf9TIy/ycc94VeppU+xOlx3MYPx/3rbdy7EVn3emf3dkQtk5u3/97Eb+9Z9l737FpIhnClx6RepnLe8UUuEvw5LfGT+S/yPp+fyk+52jXI2mSq3VydP6p1xHrbYKdtdtt1XocdDDG45TKvzg3nz7His6tunKQE/djtsiEb0xcyMcic57B7HYs99626Hzcr3HlavuksF7Oc8e7HfDzwtz/vLrS3YG7tVV5jxbicIMswlDn95lskxO5HTOOJrzX3y/XxnxLryWA8YS5MsF39vkSP9g+2/Mmzv6Lhq+G668Xm+bgAIeLekcFYTwauZH20yV7ZuWwtcSzkpzFy54PrZMBGE91klC54KiG74nRvzsn2fNdFdx+GXkhEpGgyqaFcSFYIMSTqrQChZqKPIcaYYo4l1tiSTyHFlFJO4qmWfQ455pRzLrnmVnwJJZZUcimlllZd9dBYNDXVXEuttTVu2kLjWo3vNw50130PPfbUcy+99jaAzwgjjjTyKKOONt30EwowM808y6yzLbuA0gorrrTyKquutsHa9jvsuNPOu+y622vWHll9n7WPmfs+a/aRNXcSpe/lP1njcM4vl7Cik6ickTEXLBnPygCAdsrZVWwITplTzq7qvPE+OkYZlZxplTEyGJZ1cdvX3P3J3Jd5M0T3t3lzzzJnlLr/InNGqXuTuc95e5K12Q7d+pMgVSExhSE95bdj3NfaJefQKJQ2Gd3MLqy1+bSmMvfkFju2yoEyV/V7+1XPp1Z1bFLZ1+RNudzMUGfeu1muEttqbUeG1GPNfeycZ9zZ66K2pVVH7IUbZiqv72WN7dNxgTy9rk5y9+abev9yY8asW58bM6PUYypt9NVtzLtWhjoAtylkfzGxbGv87nSYvoS0g44RMx0rYn8fWw/RbhNL63uMvXaya7iat2M2ZbSvTgx5Q9653cd2YzqBY2ZbxcOV3QbjWinv3C8uGvquMc8BvJ6eyHme0LxGxjCLExjNKbVpQ56JMWlqfvdZuGyLe7S+1h3Vt0F9PZOpPU/mHVH/NqB+fgjn+/PM48RyrvwICpdTWE5Qrus1nt+EU0Lri5PfxPRNYCS8nofUPInphxP9h8C8ou1tSKGRf4zoz2BqfhDVH4HUPEPp34DUfAG2X4PUPEPp34DUPEPp34DUPEPp34DUPEPplyfXvBw9Zy2Yvtk4uoOdGQUdD6qlC/XdGebqsD2XskxXjLmYvuRQs1BhKjETlJkgXD9nVtDHolnSJ+qozYgud7gO3yqdfxgXVXtzLtf+7tNOIAYiIp9JTlfyvghloW2R+TbCDPc7+ZR/fjU//eLTV5reUDARh6bf4WW0qyRHht98+OGzNA5ALGFiFt4LWsoTrmVf5nkreoTlySf+ROQRkDfxMH8VkCev5vcBOZ5Qs34XD/PVhycg78JB+l8C8gQM5kdY+Sowb+Ji/lVg3ryanyPle6CYnyPle6CYnyPle6CY/yRAHy/0PVK+B4r5OVK+B4r5V4F582r+kwCdC/0YKd8DxfwcKd8DxbwJCKJ/6ATX8n330zsKZnMkHxDiAQ+RFg2muKz+MrfzaY2e63TmGsuWgsKNi9771YWWH75riran85nVFEPqM9OT2sSKyqj0lh3HVsR25JC4Wy0z1OGiXTHNRPdXs78s9zxAuJJUAg7nXLSp4RvsxL5G3lN9XXDzox+UxJgDzRRXNHO2t6jZmK/c/ZiSF4leL3nh6yx9mGtiQZnlFfoVZaNA5pxpy4+VPfCLceAicuk7lEqHjCm3k8FUhkylx8NwbRN5XXOvfq1QBn6vM0ASHy3ywHpP8m2euKO5yJmfMY82RgMCCcMVx8xd6c9QrZvLIVVGSFVrLDTyWXYEKrxLtYe5Utiuky8kjF+UZMI3ZkwYxkaeEFGwnJk4ul7OxVAOvXJDcjA8to1LASAONJ/n2iiItWT8Iy0ff9R82q2hX2xcs5mOS0thoA6GtZW54d3k367URx8Zc2vD8ki40JfFaoKbmcNGe/m2kB1x7p5LHCYgoLCU/LXjvMg+wSErZfqRbOrrWtPGtlMsBNrmK9sVJlLNVUBBsGxfabZwmXGlQQxTL3J0FamHlZ0+5oocWzXhV0evi4FaZJgHST1RfjFSfM5qLoMs925S1hLAzsEiYq+GnbWVIXJqrjhvMi6NmAjwKtle4Kiig0ZBYDX0bO+ztbSvCrKdiwQwSPryjXBKICG3bhCOHselrGF07Q4hkWBHLrMiR9QngEhjNXA03O41RFcHVry23g6yc/R41+2ry/jtar1NKxwgAidQhQ1HDDJTpGYmRyZsCzHAgQmewWTP7YftEn3o7LIK2hjo3/J8lxjqC/Fe0sNhUuanoMzMiYpK1IQbCbPeHcGYyOjsppZXWnGLSI3jljDbZB/wCv4L6z6Rwy0Tb4lRamZTvrMD9rwy1XRxX9SrtbkEe91NIWSCl/b0ye1Nygb4W7o311la9kkI2oEuzS0B8dUcwhYw86dzroExeEy8GHrcwKePWmqwbheiTTERr15hUWcYSo6hu7K2Gytun+YSODLTy764YJeYWpWRwFjSanSqkO1sMAPwntLhVzYhagFgjrroOvwKM+62vLQzo591UmOKGExT4MmJA6k9X2od4BgFlUtta0f4KCyti6RSPWh2I5ctdCwVLEWATg84tKIqgv598QNkxLZsvyijwIfJNxdN63lady+mNFIYrK+thDha7DZ7ZcuS6+k5fWvGTr1EC0HxmMJYYcpki4FKqTxuOEbvDC5QYxlG9JaCyKXl2Ggd2ATKbUDqtA5+dcutGEnGRRQ/KTKzW4Qb6mzUcKK69EeKlkK7XMoJqoD1Bvhu1QX4Dv8WM5VA+ASTeJW7Eoz3geDtPKdjtnDC2FDR8ilHC9/mFGUQ466QmlwesBoejrrSpOXgsyBNCl6A7D76ksuFQUpaiRLERrZ4prEq9XRa84IKSdTMCz49nrZSorMW36CU1r3B74FIWiRFx7zwznR8WFftYtFBh6eVUnDQNU0LDq7OM6XEuCwwWsWTDErRTCZuw3Q+3s2PHgkhD6bYsw9wG6x5TDKtIDOh1QEPPIh4AHUUgJa+dgLZlHylvEvcuNJJugNsmJzvxUb6rRbClJACnZFEURb0Tm88lMKpk7iMHMyqZF3MeVgGFOwwm+slwHqc6JS1cPtPmfBacyeba9ScO36xx0WLlhopxV8QXroy36Jme4eMoTHuUyGiTOY3VF3o27oRKAswjFWCWoUSrod5NZ/da/zK19b34so5AahBXwOtYvKtx+ItVm4hk9JDrfkvPy2ndpKWF+n+zWpJo+zmYJGuRYRLC5bM+lax9AmExLUeGlY9fF3x/owUaIFCdGupQgFyiISDo/FmPaIBbBA8sT9aI4CLVXXpKf5d6JrqPYUJhBgCHBt8fJhj+NuNV5GKaBvOQSl5+Dh5Yzdv50IlqZqQD4sf10OxjRa3E7KtjJ7MVUeiRTFtEOIadQ8aSvYtDqRSIs2QGm043zJsSjN4xBKp02JIRa3VgHoxGZVC82X8m1ZdSfBCl0KYbm2VZKKv8F0YAerlqrMSgVMD8JVF0s6zYryMu/LsVM1IfDHvBFLRkmWvlTysQfyogYgSUWlOCAil55av0afQKds5jhirBrjTxy0QAbrXRGC5OYVtwJRP+75Qi4GvBSAD7OnpSCpqbt/LMJoGNGeULLiVwo16UvrhFe1BiUykL1Gi3vlqr0hP0SRtkZykOWCqGI2oEn3I/WCoffVVkF+UxLaDoNJfLN9vWhcnULCNnjOikkgO04wUIf0lN7sMIn4zXDCCGvDquLUEAMXBnNQiqX0aLaxfEyxH1wOXyAr6/OaEjBSAGOowa8NEYPoUAZE9HcvRdMbj3fXyysSoi5Y8yp7+Q03aWVuNXWQwDW2Gq2Q9gFvR5VSRvs4LU7AGxbgbemwXRgBFw5qTQNDMOlaCpNvk9LiCTmxoJsTPMrUCJ4UqNgNJjqZWUSegfotaqDl/oXZOpa1+wJuRlBtck8c2DMWHRARhtksD8x72BN8UxQWuyDLVSZxRSrGip8OpxThVi16VhlTtfGKefiQphhTsVqDlIlVGzYY+rXAAPwCMJDbi+/MaWqw0KX71Ee6Lah99anHUBs/cJSKjfUMef7jDfE0e5dg3MdExcLJvt3krYjyPzXGLvsK8aFLDQDAYDrKxIXVQZMuhkCVdhEGso5wE0p2aRfUlYqjnLViTSi+lmCB3BupMxjbZeBFd3T341pr8ckLYeY2AgsKMDIsuBuzydfeCdI2R1DZwCs/wVbOLCnZgSLe8E4wBFysqilKskh1aEk3hQkiU4Af/TezSop9BJAQujnvNHwWjnllBPw0Uj+JRN1T4hkZSiNJcla4eE94YuFMUNTpYooj8GxaTykx6wFLdvJtMx16VhB2DL3C8MYHA6LtVn4NBungzMBMNjnwyR8pTD9EC5bYN7ndYGDU6CA2dkNXI9UiQqmsefJ0nwkGlEdBtzesNsd4ot+RRrUW2NnnjQrdS5HRQuGZHXI2HS8WGWJgk/CcM35YGl6lsbvpDR8HxGb2xJpflsn3B90GtMO4eUWoSXqTVe6oL5VWYHQF1qSx5f1qEw25QnFwXVrF7JGigZm9oDAO7FeCRTBaoRngFukDrI/AAEw5jeovKRz8zI2QzLW7SwWhC8C/RaNYHyJ9KvtB0AIL8bpdqQ7igxkZYgCVrgLAh0osD+25/W3r708ooY7Nq7jiASddUo+8o7qj0O/AkL44H4aqrFluGlmrUE5GadwENu5yeZvW7V8zLNmgH+TUSZE1+xvIXzUzL83Rp26ye+pIM5iXJinhEEsGtqKPivbzIVplyijbKiDug6QvPgbZFXCA+EIZZ3Iw8iikc54an02rRjFJfEH4JpkXoFxm0QOkU2wampXBRv74n6fou4aJQIBHz9alxQTBYcagWa57p/1grxOMsR36HKJyPYWEzb8cl8iG8YnOvRZykpX64GH1eJ8BL2awVykIJDJQPcaEJkSuKskEQp98wd/gd3Ik+guw7NYXeDhkx+Id8zWf2fU6+Lr0jX1j9PfmazxT7d+RrPrNvRCxi9/mgrqRFqzSPr9ZCmEL/TCKOC2JLp1cxHx9OoLvG0bQmQ1dFo9jThcWOpO3uyCSdfkr99XRwzSVN/tiZpUCznomTy8vLlG6IsmoEDo00hbtAs6YTLkY9mBB9fJmELhlk/Rq5zwzjif52IKxIdOqWkgUIF1IF5E3ghr+B3TwUCIXEs0rkOZN2RAceCVC3RjnCzD1Ammtq90AFpLguAotNSSUeAYbx0LOoeBEVfE5vISN3TNAGgzNzSHQi6BoeuzhxVwskS5ZQa0DoHMkKrYnid0o9CznZ+RxQUdENE5N1MVhsKMG2jF++VcHnAn5Gi1PZXgspsVd3ykK++Si8eGlg9SZh4xm9dt9AkjcLJwRd8vzPQaZgzkLChWkHFzF95Ti3y9f+jzTiuvbGMB90EWFC2NGodkqWFgOXUmHgjLulONWKm9QKiDQdw7hOBEdAneNlkIx4dghx+EtLgCI3ZqdsYvfpfJDvIJt6Pkpn7ajvtLaRaUxZm7ko/mPhke+wLwJCQ8GlojRl4+S6kRkr8z1+ScrSWtCWk0E4RoRt7RCrpdtLgWcoBNcDv4IWzBZciNhHhZI2lFsi5VWrsV62P3uITJtT4sbUEC3fEPbwBqOXfEalea3I1U3Tw0z06+xoUeEDq1rJGLRZYG4nFE+tbBpsKUOHX+kMXRyZEu5dLj1fXtIUdYOs5mqyEBfJpknNFiQJndaT6AIODjPB4Y1I0k2dDPdAJEl6ac09TshSDZuhTu1usVgM79DIc1zUtFfcMGLoI3r9yBSj080iKr08HhMQkUUPHL3E88HQs2f0iYgPWwZAyfA10NwL9JqITnEJKYDjqOFCWFFKkEYhlFpT4EZRC8NEeSyED9YWX0Q1DwdhyespTAitZWkCVau7RC9ixs7id0PZIG21agRgOQYuL1QyTgSJgsJmElxkUrPaGeQ3YtRiw5FEVeaHXIJnOuCxjrzEY3D8Nc9Kbtm1aMMT2uUwcb73J5x1QTO1nn4T9ZOP9alU74naC/O3+ER1m39L/JT8stWhj7Ta5kqlNjtiD1m0wAx25oKymT/OhARf/CD9KLGGysZ0V2we8Hfekhe6czAOjevgaugYCdmBtKUeaZv0QObgEOULVfSAGYR2OnXUztx3r+YCc3jj0DrUgsTSpkjJ7MXdafr8Ab1gmu/1iI1MhVL0fKNK5BDOWAZScRis1V7ahdGOjFpFyykNBYdiJpwUAV+gBNHmUOiltWfY2jK5oI2mjTykVW014NDKdDlQBSGAYyq6PJ4d9XsnC60t3bIfupQTmFqPZx7S9N1LUGXTcIwjkiER1LrgtDxHka/FJODYvTZEMFJUQdGDpzjqUUqXypXcZW0awZ0a3GUPmQqWOEOW2NVtky2SBpkNTT9JJ4jxBJw/4AAZIJCJi+t66sC3XA2GRqiapLM1Sv9hVzAR9PuCLnVpoYe0CK2iu7sx3aj/ccxwsp5yGWTdCBBAvRL3gknbOM8Z+l1NUNcilpQ0bUgmDdVH88pq3JeKARbL8soGADPwqfuhobHeTSo50BqqmNqV5CUZaFZasIY41XwHRlgPo5LWjqLkgTUo4IpWgeEZeEczXA0HhBU7y6cQQYGfCT36DuwHBCyZJdxIxK4Nk7cvjAnO1oXmveCV472ziPaHa/IYNNsuBkB29HhOD2qWkoGvvPQKNpma1s+zmUjq82CSCktaCxB5oAIaV2GKXYoV01A92JeUH4rX9niNjhF6cUPTGwJRz5TgOQWCICJbMDNrgS6O0tjqZLCEprfHo+Tlgff7VUZzLzNKwH21BPn4rGsBOmK98SpjtLdrkFpkNP/FGqSWIJnaA2XWx88q8Oev5ncnfLWpKDbz1Uf9ftTzPijX27DcWwiYuea9zPugvP/wc0i0R/gRlA8xMX8dlA+v5vdBeQ4V8xusfAcV8xusfAcV8x+E56sLfY2V76BifoOV76BifoOV7+Zmrv8oSOY3WPkOKuZnWMGYa9d1QZGFs+tadgFzurSik7S2bLyE3lnixqqlx87QneWz76040sUYscf26qbt1ZYGrP+rjnaUZxu0xSCeHeNnnY9m7sK9RXOdx8rOMtpyt4Mvb+LExnSbaLKuTocUz1f6/rpX++J3p5/dq7SD88Du3hxSjISeNoWezDMuunruejKLwNZatzZ1tycnPs4DJTSRcANyT6nGgzE0LC0XhYbrGMOjcLWEpN0C2tl57169T/x4nnkfGjTZCQ1Z04bQs4+n6dEGJnVVpJaWup4G1bw/db+E5QSFIJ0NQ8L4HVJF9HoaUPPFiWcL6h0WbUHV/5+ipFu9vQRUu8P+hNS8j+l3p7+G5wSHY3d4rjuw5keR/XzqJ9SZV9j9JrJP4GqeA+4fY/sJrOY7tP4GrOY7tP4GrOY7tP4GrOa7mP4GrOa7iP4GrOY7tL7E9MstjG8uaj5j+LEL29pUw9Yu7NZw16HOM0mHjD2bsNGmzd7MWbb2jOb4oE5RrrbGQcvo20nwp1Y8/x8vRQvx+B/EjQAAAYVpQ0NQSUNDIHByb2ZpbGUAAHicfZE7SMNQFIb/pmpFKg52kOKQoTqIBV+Io1ahCBVCrdCqg8lNX9CkIUlxcRRcCw4+FqsOLs66OrgKguADxMXVSdFFSjw3LbSI8cLhfvz3/j/nngsItRLTrI4xQNNtMxmPienMqhh4RRfCVOMYkZllzElSAp7r6x4+vt9FeZb3vT9Xr5q1GOATiWeZYdrEG8TTm7bBeZ84xAqySnxOPGpSg8SPXFca/MY577LAM0NmKjlPHCIW822stDErmBrxFHFE1XTKF9INVjlvcdZKFdbsk78wmNVXlrlONYg4FrEECSIUVFBECTaitOukWEjSeczDH3b9ErkUchXByLGAMjTIrh/8D37P1spNTjSSgjGg88VxPoaAwC5QrzrO97Hj1E8A/zNwpbf85Row80l6taVFjoC+beDiuqUpe8DlDjDwZMim7Ep+KiGXA97P6JsyQP8t0LPWmFvzHKcPQIpmlbgBDg6B4Txlr3u8u7t9bv/eac7vB6nbcr08iu8fAAAAGFBMVEUrAPgATf8bev9puf911fqxw//e5P/9//xXhuboAAAAAWJLR0QAiAUdSAAAAAlwSFlzAAAuIwAALiMBeKU/dgAAAAd0SU1FB+MGGgc5HYQtdjEAAAGxSURBVGje7dq9boMwEABgCsTsVaOsiFJlpW1UVhL8AJWHZKWtqqykEfD6LT8G7LNNEEuH84Ts47Nj7LOHWI+vi8qLFVeLyhUBBBBAAAEEEEAAAQQQ+N9AYbXFPgqtDFZ9/lXdvUEgpE1J/dXQVljrc1V9j6tK397VUY4OoDQifbB1ah8+BsHv4vYrLUCjMw8+8aBsyx8eeFRCtEDaNeXeMPJ195scCvqBAPXbFhvO+PsQ1PejAJLGzrfg/cIdAXwICuDQvOrDAWS7MZB6OoDWLSWBwD0VimMELnCBlq4IJFqg7jyDA7iEInCITUAAgVx8v5sEHUDMH7GP081B6UEgkIEnA1AoAEcGAsM6uMJlVLkyEBlW4k98A5AY9sISoNklEsDmAM0mkeaAzZiDNiNJX4Hd/BV4TiwVgHkdyFmZQMC8EjfysoOAeS/IQAYBeTfuYxOQxwAw5wMZEDMSm85IMiDmRDadEwEgZGU2nZUBIJwLbPpcgEA+qnKmTyYIKM/GUHs2KoDhdCbgdH52qmlg3v1go7y/KG4oX+obCl7zEEAAAQQQQAABBBBAAABL/z7wC4zny3zeZuM6AAAAAElFTkSuQmCC
      mediatype: image/png
  version: 0.0.1
  maintainers:
    - email: baiju.m.mail@gmail.com
      name: Baiju Muthukadan
    - email: pavel.macik@gmail.com
      name: Pavel Mac√≠k
  maturity: alpha
  provider:
    name: Red Hat
  links:
    - name: Source Code
      url: https://github.com/pmacik/postgresql-operator
  labels:
    name: postgresql-operator
  selector:
    matchLabels:
      name: postgresql-operator
  # Install
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  install:
    strategy: deployment
    spec:
      # Role(s)
      clusterPermissions:
        - serviceAccountName: postgresql-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - "*"
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - "*"
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - apps
              resourceNames:
                - postgresql-operator
              resources:
                - deployments/finalizers
              verbs:
                - update
            - apiGroups:
                - postgresql.baiju.dev
              resources:
                - "*"
              verbs:
                - "*"
      # Deployment(s)
      deployments:
        - name: postgresql-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: postgresql-operator
            strategy: {}
            template:
              metadata:
                labels:
                  name: postgresql-operator
              spec:
                serviceAccountName: postgresql-operator
                containers: 
                  - name: postgresql-operator
                    image: REPLACE_IMAGE
                    imagePullPolicy: Always
                    command:
                      - postgresql-operator
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: postgresql-operator
                    resources: {}
  # CRD(s)
  customresourcedefinitions:
    owned:
      - name: databases.postgresql.baiju.dev
        group: postgresql.baiju.dev
        version: v1alpha1
        kind: Database
        displayName: Database
        description: Describes how an application component is built and deployed.
        resources:
          - kind: Pod
            version: v1
        specDescriptors:
          - description: PostgreSQL database image
            displayName: PostgreSQL database image
            path: image
          - description: PostgreSQL database image name
            displayName: PostgreSQL database image name
            path: imageName
        statusDescriptors:
          - description: Secret to hold access password
            displayName: Password Secret
            path: passwordSecret
            x-descriptors:
              - urn:alm:descriptor:io.servicebindingrequest
