apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: REPLACE_NAME.vREPLACE_VERSION
  namespace: placeholder
  annotations:
    alm-examples: '[{"apiVersion":"postgresql.baiju.dev/v1alpha1","kind":"Database","metadata":{"name":"demo-database","namespace":"demo-app"},"spec":{"image":"docker.io/postgres","imageName":"postgres","dbName":"postgres"}}]'
    capabilities: Full Lifecycle
    categories: 'Database'
    containerImage: REPLACE_IMAGE
    createdAt: 'REPLACE_CREATED_AT'
    description: The operator that manages PostgreSQL databases.
    repository: https://github.com/baijum/postgresql-operator
spec:
  displayName: PostgreSQL Database
  description: "The operator that manages PostgreSQL databases."
  icon:
    - base64data: REPLACE_ICON_BASE64_DATA
      mediatype: image/png
  version: REPLACE_VERSION
  replaces: postgresql-operator.v0.0.3
  maintainers:
    - email: baiju.m.mail@gmail.com
      name: Baiju Muthukadan
    - email: pavel.macik@gmail.com
      name: Pavel Mac√≠k
  maturity: alpha
  provider:
    name: Red Hat
  links:
    - name: Source Code
      url: https://github.com/baijum/postgresql-operator
  labels:
    name: REPLACE_NAME
  selector:
    matchLabels:
      name: REPLACE_NAME
  # Install
  installModes:
    - supported: true
      type: OwnNamespace
    - supported: true
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  install:
    strategy: deployment
    spec:
      # Role(s)
      clusterPermissions:
        - serviceAccountName: REPLACE_NAME
          rules:
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
              verbs:
                - "*"
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - "*"
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - apps
              resourceNames:
                - postgresql-operator
              resources:
                - deployments/finalizers
              verbs:
                - update
            - apiGroups:
                - postgresql.baiju.dev
              resources:
                - "*"
              verbs:
                - "*"
      # Deployment(s)
      deployments:
        - name: REPLACE_NAME
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: REPLACE_NAME
            strategy: {}
            template:
              metadata:
                labels:
                  name: REPLACE_NAME
              spec:
                serviceAccountName: REPLACE_NAME
                containers:
                  - name: postgresql-operator
                    image: REPLACE_IMAGE
                    imagePullPolicy: Always
                    command:
                      - postgresql-operator
                    env:
                      - name: WATCH_NAMESPACE
                        value: ""
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: REPLACE_NAME
                    resources: {}
  # CRD(s)
  customresourcedefinitions:
    owned:
      - name: databases.postgresql.baiju.dev
        group: postgresql.baiju.dev
        version: v1alpha1
        kind: Database
        displayName: Database
        description: Describes how an application component is built and deployed.
        resources:
          - kind: Pod
            version: v1
        specDescriptors:
          - description: PostgreSQL database image
            displayName: PostgreSQL database image
            path: image
          - description: PostgreSQL database image name
            displayName: PostgreSQL database image name
            path: imageName
          - description: Desired database name. If not provided, default value 'postgres' will be used.
            displayName: DB name
            path: dbName
            x-descriptors:
              - urn:alm:descriptor:servicebindingrequest:env:attribute
        statusDescriptors:
          - description: Name of the Secret to hold the DB user and password
            displayName: DB Password Credentials
            path: dbCredentials
            x-descriptors:
              - urn:alm:descriptor:io.kubernetes:Secret
              - urn:alm:descriptor:servicebindingrequest:env:object:secret:user
              - urn:alm:descriptor:servicebindingrequest:env:object:secret:password
          - description: Database connection IP address
            displayName: DB IP address
            path: dbConnectionIP
            x-descriptors:
              - urn:alm:descriptor:servicebindingrequest:env:attribute
          - description: Database connection port
            displayName: DB port
            path: dbConnectionPort
            x-descriptors:
              - urn:alm:descriptor:servicebindingrequest:env:attribute
          - description: Database name
            displayName: DB name
            path: dbName
            x-descriptors:
              - urn:alm:descriptor:servicebindingrequest:env:attribute
